### ISSUE TITLE
links in your models cannot be opened and train_net.py cannot be found

### ISSUE THREAD

**Issue by bowenroom** [Computational-Camera/Kaggle-CVPR-2018-WAD-Video-Segmentation-Challenge-Solution#1]
Hello , the links of your model in the dropbox can not be opened~Thanks for repairing it !

**Comment by Computational-Camera** [comment]
You should be able to find it from Detectron website
Here is the link https://github.com/facebookresearch/Detectron/blob/master/tools/test_net.py
