### ISSUE TITLE
JSON data

### ISSUE THREAD

**Issue by tjulyz** [Computational-Camera/Kaggle-CVPR-2018-WAD-Video-Segmentation-Challenge-Solution#2]
Thanks for you kind share!
Can you provide the json data for the labels?
I found that you transfer the original json label to json as coco, but I have not found the original json data. I can only get the png label from the competition page.
Thanks a lot!

**Comment by Computational-Camera** [comment]
I use the COCO pre-trained model provided by Detectron. You should be able to find it from the official website. To convert Appolo dataset to jason format try to use this file
Kaggle-CVPR-2018-WAD-Video-Segmentation-Challenge-Solution/solution/tools/apollo4detectron_3384.py

**Comment by tjulyz** [comment]
Yes, I have read the apollo4detectron.py carefully. But I have not found the json data. Did you transfer the label from the provided .png data or from others json data?
Thanks a lot!

**Comment by Computational-Camera** [comment]
You have to download the annotation files provided by the Apolloscapes. And use the mentioned code to do the conversion.

**Comment by tjulyz** [comment]
Got it！Thank you very much!

**Comment by tjulyz** [comment]
Hi,
I have downloaded the entire apolloscape dataset for instance segmentation. I can not find the category.json which used in your code. 
1. Have you use all the apollo data which have been provided with json annotations in apollo? Or you only use the train image provided by the challenge? 
2. Besides, it is difficult to find the relations of the data path. Can you share your data path structure.
Thanks a lot!

**Comment by tjulyz** [comment]
I have carefully debug your code for generating json file.  When processing the polygon, you use

num_seg = len(obj['polygons'][0])
seg = obj['polygons'][0]

seg = np.asarray(seg)
ann['area'] = int(cv2.contourArea(seg))
ann['bbox'] = np.array(cv2.boundingRect(seg)).tolist()
poly_list = []
poly_list.append((seg.ravel()).tolist())
ann['segmentation'] = poly_list

However, sometimes one object may be truncated by trees or poles, which make the obj['polygons'] have two lists. But you only use one here, which causes only part of the annotation and part of the box are used.

Am I right?

**Comment by Computational-Camera** [comment]
>> Have you use all the apollo data which have been provided with json annotations in apollo? Or you only use the train image provided by the challenge?

I used the Apolloscape dataset instead of the challenge. But I only used part of the dataset to reduce the training time.

**Comment by Computational-Camera** [comment]
> I have carefully debug your code for generating json file. When processing the polygon, you use
> 
> num_seg = len(obj['polygons'][0])
> seg = obj['polygons'][0]
> 
> seg = np.asarray(seg)
> ann['area'] = int(cv2.contourArea(seg))
> ann['bbox'] = np.array(cv2.boundingRect(seg)).tolist()
> poly_list = []
> poly_list.append((seg.ravel()).tolist())
> ann['segmentation'] = poly_list
> 
> However, sometimes one object may be truncated by trees or poles, which make the obj['polygons'] have two lists. But you only use one here, which causes only part of the annotation and part of the box are used.
> 
> Am I right?

I think you are right. Have you looked at the statistics, are they cases?

**Comment by tjulyz** [comment]
I found that only parts of the truncated objects by trees are presented in the provided .png annotations. However, there are complete annotations for all the parts of truncated objects in the json file.  It is somewhat ambiguous.
